/*
 * This file is part of  Claim My Land.
 * Copyright (c) 2024 Mark Gottschling (gottsch)
 *
 * All rights reserved.
 *
 * Claim My Land is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Claim My Land is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Claim My Land.  If not, see <http://www.gnu.org/licenses/lgpl>.
 */
package mod.gottsch.forge.claimmyland.core.block;

import mod.gottsch.forge.claimmyland.ClaimMyLand;
import mod.gottsch.forge.claimmyland.core.block.entity.BorderStoneBlockEntity;
import mod.gottsch.forge.claimmyland.core.block.entity.FoundationStoneBlockEntity;
import mod.gottsch.forge.claimmyland.core.network.CMLNetwork;
import mod.gottsch.forge.claimmyland.core.parcel.Parcel;
import mod.gottsch.forge.claimmyland.core.registry.ParcelRegistry;
import mod.gottsch.forge.gottschcore.block.FacingBlock;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityTicker;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.EnumProperty;
import org.jetbrains.annotations.Nullable;

import java.util.Optional;

/**
 * @author Mark Gottschling on Sep 14, 2024.
 * a foundation stone can only be used to display a potential parcel and to claim a parcel.
 * it can only be generated by using a deed ie not craftable or available in the creative menu.
 */
public abstract class FoundationStone extends BaseEntityBlock implements EntityBlock {
    public static final EnumProperty<Direction> FACING = EnumProperty.create("facing", Direction.class);

    public FoundationStone(Properties properties) {
        super(properties);
        this.registerDefaultState((BlockState)((BlockState)this.stateDefinition.any()).setValue(FACING, Direction.NORTH));
    }

    @Override
    protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
        builder.add(FACING);
    }

    @Override
    public RenderShape getRenderShape(BlockState state) {
        return RenderShape.MODEL;
    }

    /**
     * execute the block entity ticker
     * @param level
     * @param state
     * @param type
     * @return
     * @param <T>
     */
    @javax.annotation.Nullable
    @Override
    public <T extends BlockEntity> BlockEntityTicker<T> getTicker(Level level, BlockState state, BlockEntityType<T> type) {
        if (!level.isClientSide()) {
            return (lvl, pos, blockState, t) -> {
                if (t instanceof BorderStoneBlockEntity entity) { // test and cast
                    if (entity.getCoords() != null) {
                        entity.tickServer();
                    }
                }
            };
        } else {
            return null;
        }
    }

    @Override
    public void onRemove(BlockState state, Level level, BlockPos pos, BlockState state2, boolean b) {
        if (!level.isClientSide() && level instanceof ServerLevel serverLevel) {
            if (!serverLevel.getServer().isRunning()) return;
            FoundationStoneBlockEntity blockEntity =
                    (FoundationStoneBlockEntity) level.getBlockEntity(pos);
            if (blockEntity != null && blockEntity.getParcelId() != null) {
                Optional<Parcel> parcel = ParcelRegistry.findByParcelId(blockEntity.getParcelId());
                ClaimMyLand.LOGGER.debug("FoundationStone.onRemove: parcelId={}, parcelPresent={}",
                        blockEntity.getParcelId(), parcel.isPresent());
                if (parcel.isPresent()) {
                    // committed parcel — hide the visual border
//                    CMLNetwork.syncBorderVisibilityToTrackingPlayers(
//                            serverLevel, parcel.get(), false, 0, pos.getY());
                    CMLNetwork.syncBorderVisibilityToDimension(serverLevel, parcel.get(), false, 0, pos.getY());
                    BorderStoneBlockEntity.ACTIVE_BORDER_STONES.remove(blockEntity);
                } else {
                    // phase 1 preview — parcel never committed; remove from client registries
                    CMLNetwork.removePreviewParcelFromTracking(
                            serverLevel, blockEntity.getParcelId(), pos);
                }
            } else if (blockEntity == null) {
                ClaimMyLand.LOGGER.debug("FoundationStone.onRemove: blockEntity is NULL at pos={}", pos);
            } else {
                ClaimMyLand.LOGGER.debug("FoundationStone.onRemove: parcelId is null");
            }
        }
        super.onRemove(state, level, pos, state2, b);
    }

    @Override
    public BlockState getStateForPlacement(BlockPlaceContext context) {
        BlockState blockState = super.getStateForPlacement(context);
        blockState = blockState.setValue(FACING,
                context.getHorizontalDirection().getOpposite());
        return blockState;
    }

    @Override
    public BlockState rotate(BlockState state, Rotation rot) {
        return state.setValue(FACING, rot.rotate(state.getValue(FACING)));
    }

    @Override
    public BlockState mirror(BlockState state, Mirror mirrorIn) {
        return state.rotate(mirrorIn.getRotation(state.getValue(FACING)));
    }
}
